// Generated by tools/import-omip-flow-tables.mjs from public OMIP tables.
export const FLOW_OMIP_SOURCE_PAGE_IDS = {
  "1": 1,
  "2": 2,
  "3": 3,
  "4": 4,
  "5": 5,
  "6": 6,
  "7": 7,
  "8": 8,
  "9": 9,
  "10": 10,
  "11": 11,
  "12": 12,
  "13": 13,
  "14": 14,
  "15": 15,
  "16": 16,
  "17": 17,
  "18": 18,
  "19": 19,
  "20": 20,
  "21": 21,
  "22": 22,
  "23": 23,
  "24": 24,
  "25": 25,
  "26": 26,
  "27": 27,
  "28": 28,
  "29": 29,
  "30": 30,
  "31": 31,
  "32": 32,
  "33": 33,
  "35": 35,
  "36": 36,
  "37": 37,
  "38": 38,
  "39": 39,
  "40": 40,
  "41": 41,
  "42": 42,
  "43": 43,
  "44": 44,
  "46": 46,
  "47": 47,
  "49": 49,
  "50": 50,
  "51": 51,
  "52": 52,
  "53": 53,
  "55": 55,
  "56": 56,
  "57": 57,
  "58": 58,
  "59": 59,
  "60": 60,
  "61": 61,
  "62": 62,
  "63": 63,
  "64": 64,
  "65": 65,
  "66": 66,
  "67": 67,
  "68": 68,
  "69": 69,
  "70": 70,
  "71": 104,
  "72": 105,
  "73": 106,
  "74": 107,
  "75": 108,
  "76": 109,
  "77": 110,
  "78": 111,
  "79": 112,
  "80": 113,
  "81": 114,
  "82": 115,
  "83": 116,
  "84": 117,
  "85": 118,
  "86": 119,
  "89": 137,
  "90": 123,
  "91": 136,
  "92": 135,
  "93": 134,
  "94": 133,
  "95": 132,
  "96": 131,
  "97": 130,
  "98": 129,
  "99": 125,
  "100": 124,
  "101": 128,
  "102": 126,
  "104": 127,
  "105": 163,
  "106": 164,
  "107": 165,
  "108": 176,
  "109": 166,
  "110": 167,
  "111": 168,
  "112": 171,
  "113": 172,
  "114": 173,
  "115": 174,
  "116": 175,
  "117": 177,
  "118": 178,
  "119": 179,
  "120": 180
} as const
export const FLOW_OMIP_TABLE_SOURCE_URLS = {
  "1": "https://app.fluorofinder.com/omips/1",
  "2": "https://app.fluorofinder.com/omips/2",
  "3": "https://app.fluorofinder.com/omips/3",
  "4": "https://app.fluorofinder.com/omips/4",
  "5": "https://app.fluorofinder.com/omips/5",
  "6": "https://app.fluorofinder.com/omips/6",
  "7": "https://app.fluorofinder.com/omips/7",
  "8": "https://app.fluorofinder.com/omips/8",
  "9": "https://app.fluorofinder.com/omips/9",
  "10": "https://app.fluorofinder.com/omips/10",
  "11": "https://app.fluorofinder.com/omips/11",
  "12": "https://app.fluorofinder.com/omips/12",
  "13": "https://app.fluorofinder.com/omips/13",
  "14": "https://app.fluorofinder.com/omips/14",
  "15": "https://app.fluorofinder.com/omips/15",
  "16": "https://app.fluorofinder.com/omips/16",
  "17": "https://app.fluorofinder.com/omips/17",
  "18": "https://app.fluorofinder.com/omips/18",
  "19": "https://app.fluorofinder.com/omips/19",
  "20": "https://app.fluorofinder.com/omips/20",
  "21": "https://app.fluorofinder.com/omips/21",
  "22": "https://app.fluorofinder.com/omips/22",
  "23": "https://app.fluorofinder.com/omips/23",
  "24": "https://app.fluorofinder.com/omips/24",
  "25": "https://app.fluorofinder.com/omips/25",
  "26": "https://app.fluorofinder.com/omips/26",
  "27": "https://app.fluorofinder.com/omips/27",
  "28": "https://app.fluorofinder.com/omips/28",
  "29": "https://app.fluorofinder.com/omips/29",
  "30": "https://app.fluorofinder.com/omips/30",
  "31": "https://app.fluorofinder.com/omips/31",
  "32": "https://app.fluorofinder.com/omips/32",
  "33": "https://app.fluorofinder.com/omips/33",
  "35": "https://app.fluorofinder.com/omips/35",
  "36": "https://app.fluorofinder.com/omips/36",
  "37": "https://app.fluorofinder.com/omips/37",
  "38": "https://app.fluorofinder.com/omips/38",
  "39": "https://app.fluorofinder.com/omips/39",
  "40": "https://app.fluorofinder.com/omips/40",
  "41": "https://app.fluorofinder.com/omips/41",
  "42": "https://app.fluorofinder.com/omips/42",
  "43": "https://app.fluorofinder.com/omips/43",
  "44": "https://app.fluorofinder.com/omips/44",
  "46": "https://app.fluorofinder.com/omips/46",
  "47": "https://app.fluorofinder.com/omips/47",
  "49": "https://app.fluorofinder.com/omips/49",
  "50": "https://app.fluorofinder.com/omips/50",
  "51": "https://app.fluorofinder.com/omips/51",
  "52": "https://app.fluorofinder.com/omips/52",
  "53": "https://app.fluorofinder.com/omips/53",
  "55": "https://app.fluorofinder.com/omips/55",
  "56": "https://app.fluorofinder.com/omips/56",
  "57": "https://app.fluorofinder.com/omips/57",
  "58": "https://app.fluorofinder.com/omips/58",
  "59": "https://app.fluorofinder.com/omips/59",
  "60": "https://app.fluorofinder.com/omips/60",
  "61": "https://app.fluorofinder.com/omips/61",
  "62": "https://app.fluorofinder.com/omips/62",
  "63": "https://app.fluorofinder.com/omips/63",
  "64": "https://app.fluorofinder.com/omips/64",
  "65": "https://app.fluorofinder.com/omips/65",
  "66": "https://app.fluorofinder.com/omips/66",
  "67": "https://app.fluorofinder.com/omips/67",
  "68": "https://app.fluorofinder.com/omips/68",
  "69": "https://app.fluorofinder.com/omips/69",
  "70": "https://app.fluorofinder.com/omips/70",
  "71": "https://app.fluorofinder.com/omips/104",
  "72": "https://app.fluorofinder.com/omips/105",
  "73": "https://app.fluorofinder.com/omips/106",
  "74": "https://app.fluorofinder.com/omips/107",
  "75": "https://app.fluorofinder.com/omips/108",
  "76": "https://app.fluorofinder.com/omips/109",
  "77": "https://app.fluorofinder.com/omips/110",
  "78": "https://app.fluorofinder.com/omips/111",
  "79": "https://app.fluorofinder.com/omips/112",
  "80": "https://app.fluorofinder.com/omips/113",
  "81": "https://app.fluorofinder.com/omips/114",
  "82": "https://app.fluorofinder.com/omips/115",
  "83": "https://app.fluorofinder.com/omips/116",
  "84": "https://onlinelibrary.wiley.com/doi/10.1002/cyto.a.24564",
  "85": "https://app.fluorofinder.com/omips/118",
  "86": "https://app.fluorofinder.com/omips/119",
  "89": "https://app.fluorofinder.com/omips/137",
  "90": "https://app.fluorofinder.com/omips/123",
  "91": "https://onlinelibrary.wiley.com/doi/10.1002/cyto.a.24738",
  "92": "https://app.fluorofinder.com/omips/135",
  "93": "https://app.fluorofinder.com/omips/134",
  "94": "https://app.fluorofinder.com/omips/133",
  "95": "https://app.fluorofinder.com/omips/132",
  "96": "https://app.fluorofinder.com/omips/131",
  "97": "https://app.fluorofinder.com/omips/130",
  "98": "https://app.fluorofinder.com/omips/129",
  "99": "https://app.fluorofinder.com/omips/125",
  "100": "https://app.fluorofinder.com/omips/124",
  "101": "https://app.fluorofinder.com/omips/128",
  "102": "https://app.fluorofinder.com/omips/126",
  "104": "https://app.fluorofinder.com/omips/127",
  "105": "https://app.fluorofinder.com/omips/163",
  "106": "https://app.fluorofinder.com/omips/164",
  "107": "https://app.fluorofinder.com/omips/165",
  "108": "https://app.fluorofinder.com/omips/176",
  "109": "https://app.fluorofinder.com/omips/166",
  "110": "https://app.fluorofinder.com/omips/167",
  "111": "https://app.fluorofinder.com/omips/168",
  "112": "https://app.fluorofinder.com/omips/171",
  "113": "https://app.fluorofinder.com/omips/172",
  "114": "https://app.fluorofinder.com/omips/173",
  "115": "https://app.fluorofinder.com/omips/174",
  "116": "https://app.fluorofinder.com/omips/175",
  "117": "https://app.fluorofinder.com/omips/177",
  "118": "https://app.fluorofinder.com/omips/178",
  "119": "https://app.fluorofinder.com/omips/179",
  "120": "https://app.fluorofinder.com/omips/180"
} as const
export const FLOW_OMIP_CYTOMETERS = {
  "1": [
    "BD LSR II"
  ],
  "2": [
    "BD LSR II"
  ],
  "3": [
    "BD LSR II"
  ],
  "4": [
    "BD LSR II"
  ],
  "5": [
    "BD LSR II"
  ],
  "6": [
    "BD LSR II"
  ],
  "7": [
    "BD LSR II"
  ],
  "8": [
    "BD LSR II"
  ],
  "9": [
    "BD LSR II"
  ],
  "10": [
    "Beckman Coulter Navios Flow Cytometer"
  ],
  "11": [
    "BD FACSCanto 2"
  ],
  "12": [
    "BD LSR2"
  ],
  "13": [
    "BD LSR2"
  ],
  "14": [
    "BD LSR2"
  ],
  "15": [
    "BD LSR2"
  ],
  "16": [
    "BD LSR2"
  ],
  "17": [
    "BD LSR2"
  ],
  "18": [
    "BD LSR Fortessa"
  ],
  "19": [
    "BD LSR2"
  ],
  "20": [
    "BD LSR2"
  ],
  "21": [
    "BD LSR Fortessa"
  ],
  "22": [
    "BD LSR2"
  ],
  "23": [
    "Beckman Coulter Navios"
  ],
  "24": [
    "BD LSR2"
  ],
  "25": [
    "BD LSR2"
  ],
  "26": [
    "BD LSR2"
  ],
  "27": [
    "BD LSR2"
  ],
  "28": [
    "BD LSR2"
  ],
  "29": [
    "BD LSR2"
  ],
  "30": [
    "BD LSR Fortessa"
  ],
  "31": [
    "BD LSR2"
  ],
  "32": [
    "BD LSR Fortessa X20"
  ],
  "33": [
    "BD LSR Fortessa"
  ],
  "35": [
    "BD LSR II SORP"
  ],
  "36": [
    "BD Fortessa"
  ],
  "37": [
    "BD FACSAria II SORP"
  ],
  "38": [
    "BD LSR2"
  ],
  "39": [
    "BD LSR Fortessa"
  ],
  "40": [
    "BD FACSAria Fusion SORP"
  ],
  "41": [
    "BD LSR2"
  ],
  "42": [
    "Bio-Rad Ze5"
  ],
  "43": [
    "BD SORP Fortessa"
  ],
  "44": [
    "BD FACSymphony A5"
  ],
  "46": [
    "BD LSR2 SORP"
  ],
  "47": [
    "BD Fortessa"
  ],
  "49": [
    "BD LSR2"
  ],
  "50": [
    "BD FACSymphony A5"
  ],
  "51": [
    "BD FACSymphony A5"
  ],
  "52": [
    "BD LSR2"
  ],
  "53": [
    "BD LSR2"
  ],
  "55": [
    "Beckman Coulter CytoFLEX"
  ],
  "56": [
    "BD FACSymphony A5"
  ],
  "57": [
    "BD LSR Fortessa"
  ],
  "58": [
    "BD FACSymphony A5"
  ],
  "59": [
    "BD FACSAria Fusion"
  ],
  "60": [
    "BD FACSymphony A5"
  ],
  "61": [
    "BD FACSymphony A5"
  ],
  "62": [
    "BD LSR Fortessa"
  ],
  "63": [
    "BD FACSymphony A5"
  ],
  "64": [
    "BD FACSymphony A5"
  ],
  "65": [
    "BD LSR Fortessa"
  ],
  "66": [
    "BD FACSymphony A5"
  ],
  "67": [
    "BD FACSymphony A5"
  ],
  "68": [
    "BD FACSymphony A5"
  ],
  "69": [
    "Cytek Aurora 5L (UV-V-B-YG-R)"
  ],
  "70": [
    "BD FACSymphony A5"
  ],
  "71": [
    "BD FACSymphony A5"
  ],
  "72": [
    "BD LSR Fortessa"
  ],
  "73": [
    "BD LSR Fortessa"
  ],
  "74": [
    "BD FACSymphony A5"
  ],
  "75": [
    "BD FACSymphony A5"
  ],
  "76": [
    "BD LSR Fortessa"
  ],
  "77": [
    "BD LSR Fortessa"
  ],
  "78": [
    "BD FACSymphony A5"
  ],
  "79": [
    "BD LSR Fortessa"
  ],
  "80": [
    "BD FACSymphony A5"
  ],
  "81": [
    "Beckman Coulter Navios"
  ],
  "82": [
    "BD FACSymphony"
  ],
  "83": [
    "Cytek Aurora 3L (V-B-R)"
  ],
  "84": [
    "Cytek Aurora 5L (UV-V-B-YG-R)"
  ],
  "85": [
    "BD LSR Fortessa X-20"
  ],
  "86": [
    "Cytek Aurora 5L (UV-V-B-YG-R)"
  ],
  "89": [
    "BD LSR Fortessa"
  ],
  "90": [
    "BD LSR Fortessa"
  ],
  "91": [
    "Cytek Aurora 5L (UV-V-B-YG-R)"
  ],
  "92": [
    "BD LSR Fortessa"
  ],
  "93": [
    "Cytek Aurora 5L (UV-V-B-YG-R)"
  ],
  "94": [
    "Cytek Aurora 3L (V-B-R)"
  ],
  "95": [
    "Cytek Aurora 5L (UV-V-B-YG-R)"
  ],
  "96": [
    "BD FACSymphony"
  ],
  "97": [
    "Cytek Northern Lights 3L (V-B-R)"
  ],
  "98": [
    "BD FACSymphony"
  ],
  "99": [
    "Cytek Aurora 5L (UV-V-B-YG-R)"
  ],
  "100": [
    "BD LSR Fortessa"
  ],
  "101": [
    "BD FACSymphony"
  ],
  "102": [
    "Sony ID7000 7L",
    "BD FACSDiscover S8 5L"
  ],
  "104": [
    "Cytek Aurora 5L (UV-V-B-YG-R)"
  ],
  "105": [
    "BD FACSymphony A5 SE"
  ],
  "106": [
    "BD FACSymphony"
  ],
  "107": [
    "Beckman Coulter CytoFLEX S V4-B2-Y4-R3 Flow Cytometer Series"
  ],
  "108": [
    "Cytek Aurora 5L 16UV-16V-14B-10YG-8R"
  ],
  "109": [
    "Cytek Aurora 5L (UV-V-B-YG-R)"
  ],
  "110": [
    "Cytek Aurora 5L (UV-V-B-YG-R)"
  ],
  "111": [
    "Sony ID7000"
  ],
  "112": [
    "Sony ID7000 5L (UV-V-B-YG-R)"
  ],
  "113": [
    "Beckman Coulter CytoFLEX S V4-B2-Y4-R3 Flow Cytometer Series"
  ],
  "114": [
    "Cytek Aurora 5L (UV-V-B-YG-R)"
  ],
  "115": [
    "Sony ID7000"
  ],
  "116": [
    "BD FACSymphony A5 SE"
  ],
  "117": [
    "Cytek Aurora 5L (UV-V-B-YG-R)"
  ],
  "118": [
    "Cytek Aurora 5L (UV-V-B-YG-R)"
  ],
  "119": [
    "Cytek Aurora 5L (UV-V-B-YG-R)"
  ],
  "120": [
    "Cytek Aurora 4L (UV-V-B-R)"
  ]
} as const
export const FLOW_OMIP_IMPORT_MANIFEST = {
  flowOmipCount: 113,
  markerRowCount: 2372,
  sourceDirectory: "https://admin.fluorofinder.com/omips",
  importedAt: "2026-08-05",
} as const
